version: '3'

# networks
# create a network 'guacamole_net' in mode 'bridged'
networks:
  guacamole_net:
    driver: bridge
  keycloak_net:
    driver: bridge
  haproxy_net:
    driver: bridge

services:

  postgres:
    container_name: guacamole_database
    image: docker.io/postgres:14.9
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data/guacamole:/var/lib/postgresql/data:rw
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: '${GUAC_POSTGRES_PASSWORD}'
      POSTGRES_USER: '${GUAC_POSTGRES_USER}'
    networks:
      - guacamole_net

  guacd:
    container_name: guacamole_backend
    image: docker.io/guacamole/guacd:${GUACAMOLE_VERSION}
    restart: always
    networks:
      - guacamole_net
    ports:
      - "4822:4822"
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
    #deploy:
    #  replicas: 2

  guacamole:
    container_name: guacamole_frontend
    image: docker.io/guacamole/guacamole:${GUACAMOLE_VERSION}
    restart: always
    #ports:
    #  - "6443:8443"
    hostname: ${GUAC_HOSTNAME}
    networks:
      guacamole_net:
        aliases:
          - ${GUAC_HOSTNAME}
      haproxy_net:
    volumes:
      - ./openid/guacamole-auth-openid-${GUACAMOLE_VERSION}.jar:/opt/guacamole/openid/guacamole-auth-openid-${GUACAMOLE_VERSION}.jar:ro
      - ./init/guacamole.crt:/usr/local/tomcat/conf/guacamole.crt:ro
      - ./init/guacamole.key:/usr/local/tomcat/conf/guacamole.key:ro
      - ./init/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./init/cacerts:/docker-java-home/jre/lib/security/cacerts:ro
      - ./init/cacerts:/opt/java/openjdk/jre/lib/security/cacerts:ro
    environment:
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: '${GUAC_POSTGRES_USER}'
      POSTGRESQL_PASSWORD: '${GUAC_POSTGRES_PASSWORD}'
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: 'true'
      GUACD_HOSTNAME: guacd
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACAMOLE_HOSTNAME: https://guacamole:8443/#
      # https://${KC_HOSTNAME}:8443/realms/${KEYCLOAK_REALM_NAME}/.well-known/openid-configuration
      # https://guacamole.apache.org/doc/gug/openid-auth.html
      OPENID_AUTHORIZATION_ENDPOINT: https://${KC_HOSTNAME}/realms/${KEYCLOAK_REALM_NAME}/protocol/openid-connect/auth
      OPENID_JWKS_ENDPOINT: https://keycloak:8443/realms/${KEYCLOAK_REALM_NAME}/protocol/openid-connect/certs
      OPENID_ISSUER: https://${KC_HOSTNAME}/realms/${KEYCLOAK_REALM_NAME}
      OPENID_CLIENT_ID: guacamole
      #OPENID_REDIRECT_URI: https://${GUAC_HOSTNAME}/guacamole/#/settings/sessions
      OPENID_REDIRECT_URI: https://${GUAC_HOSTNAME}/
      OPENID_CLAIM_TYPE: sub
      # OPENID_CLAIM_TYPE: preferred_username
      OPENID_SCOPE: openid profile
      OPENID_ALLOWED_CLOCK_SKEW: 99999
      OPENID_MAX_TOKEN_VALIDITY: 300
      OPENID_MAX_NONCE_VALIDITY: 10
    links:
      - guacd
    depends_on:
      - postgres
      - guacd
      - keycloak

  haproxy:
    container_name: haproxy
    image: docker.io/haproxy:2.4.24-alpine
    restart: always
    ports:
      - "443:8443"
    volumes:
        - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - haproxy_net
    environment:
      GUAC_HOSTNAME: '${GUAC_HOSTNAME}'
      KC_HOSTNAME: '${KC_HOSTNAME}'
    depends_on:
      - guacamole
      - keycloak

  keycloakpostgres:
    container_name: keycloak_database
    image: docker.io/postgres:14.9
    restart: always
    hostname: keycloakpostgres
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: '${KC_POSTGRES_USER}'
      POSTGRES_PASSWORD: '${KC_POSTGRES_PASSWORD}'
      POSTGRES_DB: 'keycloak_db'
    networks:
      keycloak_net:

  keycloak:
    container_name: keycloak_frontend
    image: 'docker.io/keycloak/keycloak:${KEYCLOAK_VERSION}'
    restart: always
    depends_on:
      - keycloakpostgres
    env_file:
      - '.kc.env'
    environment:
      KC_DB_USERNAME: '${KC_POSTGRES_USER}'
      KC_DB_PASSWORD: '${KC_POSTGRES_PASSWORD}'
      #https://www.keycloak.org/server/hostname
      KC_HOSTNAME_URL: 'https://${KC_HOSTNAME}/'
      #KC_HOSTNAME_PORT: '443'
      KC_HOSTNAME_ADMIN_URL:  'https://${KC_HOSTNAME}/'
      KEYCLOAK_ADMIN: '${KEYCLOAK_ADMIN_USER}'
      KEYCLOAK_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD}'
    command: 'start'
    hostname: ${KC_HOSTNAME}
    #extra_hosts:
    #  - 'mailer:192.168.0.5'
    #ports:
    #  - "7443:8443"
    tmpfs:
      - /run
      - /tmp
      - /opt/jboss/keycloak/standalone/tmp/vfs/temp
    volumes:
    #  - ./init/application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore
      - ./init/keycloak.crt:/etc/pki/tls/keycloak.crt
      - ./init/keycloak.key:/etc/pki/tls/keycloak.key
      - ./init/cacerts:/opt/keycloak/conf/cacerts
    #  - ./config/keycloak/guacamole-client.json:/guacamole-client.json
    networks:
      keycloak_net:
      haproxy_net:
        aliases:
          - ${KC_HOSTNAME}
    deploy:
      replicas: 1