version: '3.9'

# networks
# create a network 'guacamole_net' in mode 'bridged'
networks:
  guacamole_net:
    driver: bridge
  keycloak_net:
    driver: bridge
  haproxy_net:
    name: haproxy_net
    driver: bridge

services:

  postgres:
    container_name: guacamole_database
    image: docker.io/postgres:14.9
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data/guacamole:/var/lib/postgresql/data:rw
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: '${GUAC_POSTGRES_PASSWORD}'
      POSTGRES_USER: '${GUAC_POSTGRES_USER}'
    networks:
      - guacamole_net

  guacd:
    container_name: guacamole_backend
    image: docker.io/guacamole/guacd:1.5.3
    restart: always
    networks:
      - guacamole_net
    ports:
      - "4822:4822"
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw

  guacamole:
    container_name: guacamole_frontend
    image: docker.io/guacamole/guacamole:1.5.3
    restart: always
    ports:
      - "6443:8443"
    hostname: ${GUAC_HOSTNAME}
    networks:
      guacamole_net:
        aliases:
          - ${GUAC_HOSTNAME}
      haproxy_net:
    volumes:
      - ./openid/guacamole-auth-openid-1.5.3.jar:/opt/guacamole/openid/guacamole-auth-openid-1.5.3.jar:ro
      - ./init/guacamole.crt:/usr/local/tomcat/conf/guacamole.crt:ro
      - ./init/guacamole.key:/usr/local/tomcat/conf/guacamole.key:ro
      - ./init/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./init/cacerts:/docker-java-home/jre/lib/security/cacerts:ro
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${GUAC_POSTGRES_PASSWORD}'
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
      GUACD_HOSTNAME: guacd
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
      GUACAMOLE_HOSTNAME: https://guacamole:8443/guacamole/#
      # https://${KC_HOSTNAME}:8443/auth/realms/master/.well-known/openid-configuration
      # https://guacamole.apache.org/doc/gug/openid-auth.html
      OPENID_AUTHORIZATION_ENDPOINT: https://${KC_HOSTNAME}:8443/auth/realms/master/protocol/openid-connect/auth
      OPENID_JWKS_ENDPOINT: https://${KC_HOSTNAME}:8443/auth/realms/master/protocol/openid-connect/certs
      OPENID_ISSUER: https://${KC_HOSTNAME}:8443/auth/realms/master
      OPENID_CLIENT_ID: guacamole
      OPENID_REDIRECT_URI: https://${GUAC_HOSTNAME}:8443/guacamole/#/settings/sessions
      OPENID_REDIRECT_URI: https://${GUAC_HOSTNAME}:8443/guacamole
      OPENID_CLAIM_TYPE: sub
      # OPENID_CLAIM_TYPE: preferred_username
      OPENID_SCOPE: openid profile
      OPENID_ALLOWED_CLOCK_SKEW: 99999
      OPENID_MAX_TOKEN_VALIDITY: 300
      OPENID_MAX_NONCE_VALIDITY: 10
    links:
      - guacd
    depends_on:
      - postgres
      - guacd
      - keycloak

  haproxy:
    container_name: haproxy
    image: docker.io/haproxy:2.4.24-alpine
    restart: always
    ports:
      - "443:8443"
      - "80:80"
      - "8404:8404"
    volumes:
        - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - haproxy_net
    environment:
      ENDPOINT: '${ENDPOINT}'
    depends_on:
      - guacamole
      - keycloak

  keycloakpostgres:
    image: docker.io/postgres:14.9
    restart: always
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    networks:
      keycloak_net:

  keycloak:
    image: docker.io/keycloak/keycloak:22.0.1
    restart: always
    depends_on:
      - keycloakpostgres
    env_file:
      - '.kc.env'
    environment:
      KC_DB_PASSWORD: '${KC_POSTGRES_PASSWORD}'
      KC_DB_USERNAME: '${KC_POSTGRES_USER}'
      #https://www.keycloak.org/server/hostname
      KC_HOSTNAME: '${KC_HOSTNAME}'
      KEYCLOAK_ADMIN: '${KEYCLOAK_ADMIN_USER}'
      KEYCLOAK_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD}'
    command: 'start --auto-build'
    hostname: ${KC_HOSTNAME}
    extra_hosts:
      - 'mailer:192.168.0.5'
    ports:
      - "7443:8443"
    tmpfs:
      - /run
      - /tmp
      - /opt/jboss/keycloak/standalone/tmp/vfs/temp
    volumes:
      - ./init/application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore
      - ./init/cacerts:/usr/lib/jvm/java-11-openjdk-11.0.6.10-0.el8_1.x86_64/lib/security/cacerts
      - ./config/keycloak/guacamole-client.json:/guacamole-client.json
    networks:
      keycloak_net:
      haproxy_net:
        aliases:
          - ${KC_HOSTNAME}
    deploy:
      replicas: 1